/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LogicalScreenDescriptor {
  width: number
  height: number
  globalColorFlag: boolean
  colorResolution: number
  sortedFlag: boolean
  globalColorSize: number
  backgroundColorIndex: number
  pixelAspectRatio: number
}
export interface Frame {
  gcd: GraphicsControlExtension
  im: ImageDescriptor
  localTable: Array<Color>
  indexStream: Array<number>
}
export interface ImageDescriptor {
  left: number
  top: number
  width: number
  height: number
  localColorTableFlag: boolean
  interfaceFlag: boolean
  sortFlag: boolean
  localColorTableSize: number
}
export interface GraphicsControlExtension {
  disposalMethod: number
  userInputFlag: boolean
  transparentColorFlag: boolean
  delayTime: number
  transparentColorIndex: number
}
export interface Color {
  red: number
  green: number
  blue: number
}
export class Gif {
  version: string
  lsd: LogicalScreenDescriptor
  globalTable: Array<Color>
  frames: Array<Frame>
  processFrames(): Array<Buffer>
}
/** */
export class Decoder {
  static decode(filePath: string): Gif
}
